import Head from "next/head";
import Header from "../components/Header";
// import Navbar from '../components/Navbar';
// import styles from '../styles/Home.module.css';

export default function Browse() {
  return (
    <>
      <Head>
        <title>Browse | Tickzone</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />
    </>
  );
}
