import Head from "next/head";
import Brand from "../components/Brand";
import FormSignin from "../components/FormSignin";
import Navbar from "../components/Navbar";

export default function Signin() {
  return (
    <>
      <Head>
        <title>Sign in | Tickzone</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <section className="bg-navy">
        <Navbar />
      </section>
      <section className="login header bg-navy">
        <div className="container">
          <div className="d-flex flex-column align-items-center hero gap-5">
            <div>
              <div className="hero-headline text-start">Sign in</div>
            </div>
            <FormSignin />
          </div>
        </div>
      </section>
      <Brand className={"pt-0 bg-navy"} />
    </>
  );
}

export async function getServerSideProps(context) {
  const { token } = context.req.cookies;

  if (token) {
    return {
      redirect: {
        destination: "/",
        permanentRedirect: false,
      },
    };
  }

  return {
    props: {},
  };
}
